//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okul_Takip_Sistemi.Dosyalar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Okul_Takip_Sistemi.Dosyalar.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Adres_Beyan_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Adres_Beyan_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BAP_Başvuru_Formu {
            get {
                object obj = ResourceManager.GetObject("BAP_Başvuru_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Belge_Başvuru_Formu {
            get {
                object obj = ResourceManager.GetObject("Belge_Başvuru_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ÇAP_YDP_Başvuru_Formu {
            get {
                object obj = ResourceManager.GetObject("ÇAP_YDP_Başvuru_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Çift_Ana_Dal_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Çift_Ana_Dal_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ders_Muafiyet_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Ders_Muafiyet_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] İlişik_Kesme___Kayıt_Silme_Talep_Formu {
            get {
                object obj = ResourceManager.GetObject("İlişik_Kesme___Kayıt_Silme_Talep_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kayıt_Dondurma_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Kayıt_Dondurma_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kurumiçi_Yatay_Geçiş_Başvuru_Formu {
            get {
                object obj = ResourceManager.GetObject("Kurumiçi_Yatay_Geçiş_Başvuru_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kütüphane_Kayıp_Kitap_Formu {
            get {
                object obj = ResourceManager.GetObject("Kütüphane_Kayıp_Kitap_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lisans_Yan_Dal_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Lisans_Yan_Dal_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mazeret_Dilekçesi_Lisans {
            get {
                object obj = ResourceManager.GetObject("Mazeret_Dilekçesi_Lisans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mazeret_Dilekçesi_Önlisans {
            get {
                object obj = ResourceManager.GetObject("Mazeret_Dilekçesi_Önlisans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Not_İtiraz_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Not_İtiraz_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Öğrenci_Bilgi_Formu {
            get {
                object obj = ResourceManager.GetObject("Öğrenci_Bilgi_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OkulTakipSistemiWordDosyas {
            get {
                object obj = ResourceManager.GetObject("OkulTakipSistemiWordDosyas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Önlisans_Yan_Dal_Dilekçesi {
            get {
                object obj = ResourceManager.GetObject("Önlisans_Yan_Dal_Dilekçesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tek_Ders_Sınav_Başvuru_Formu {
            get {
                object obj = ResourceManager.GetObject("Tek_Ders_Sınav_Başvuru_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yabancı_Uyruklu_Öğrenci_Bilgi_Formu {
            get {
                object obj = ResourceManager.GetObject("Yabancı_Uyruklu_Öğrenci_Bilgi_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yatay_Geçiş_Başvuru_Formu {
            get {
                object obj = ResourceManager.GetObject("Yatay_Geçiş_Başvuru_Formu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yatay_Geçiş_Başvuru_Formu__Ek_Madde_1_ {
            get {
                object obj = ResourceManager.GetObject("Yatay_Geçiş_Başvuru_Formu__Ek_Madde_1_", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
